name: macOS Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     SysexLiveMacOS.zip

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version:      ${{ env.QT_VERSION }}
        host:         macos
        target:       desktop
        arch:         x86_64
        dir:          ${{ runner.temp }}
        modules:      qtmultimedia
        setup-python: false
              
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/build
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}/SysexLive/SysexLive.pro
            make
            cd release
            macdeployqt SysexLive.app

    - name: Zip build
      working-directory: ${{ runner.temp }}
      run:  |
            7z a SysexLiveMacOS.zip ${{ runner.temp }}\build\* -r

    - name: Save build artifact
      uses: actions/upload-artifact@4
      with:
        name: ${{ env.ARTIFACT }}
        path: ${{ env.SOURCE_DIR }}/build/${{ env.ARTIFACT }}
