name: macOS Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2

jobs:
  build:

    runs-on: macos-10.13

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version:      ${{ env.QT_VERSION }}
        host:         macos
        target:       desktop
        arch:         x86_64
        dir:          ${{ runner.temp }}
        modules:      qtmultimedia
        setup-python: false
              
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/build
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}/SysexLive/SysexLive.pro
            make
            cd release
            macdeployqt SysexLive.app

    - name: Zip build
      working-directory: ${{ runner.temp }}
      run:  |
            7z a SysexLive.zip ${{ runner.temp }}\build\* -r
